services:
  kong:
    image: kong:3.6
    restart: always
    environment:
      KONG_DATABASE: "off"                          # use config file YML
      KONG_DECLARATIVE_CONFIG: /kong/kong.yml
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_PROXY_LISTEN: 0.0.0.0:8000
    volumes:
      - ./kong.yml:/kong/kong.yml
    ports:
      - "8000:8000"   # proxy cho client
      - "8001:8001"   # admin API

