name: Lint and Format Check

on:
  push:
    branches: [main, master, develop, benchmark, hair, tu]
  pull_request:
    branches: [main, master, develop, hair, tu]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install root dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint:fix

      - name: Check Prettier formatting
        run: npm run format
